package com.filipeduraes.workshop.client.viewmodel;

public enum MaintenanceRequest
{
    REQUEST_OPENED_APPOINTMENTS,
    REQUEST_USER_SERVICES,
    REQUEST_DETAILED_SERVICE_INFO,
    REQUEST_REGISTER_APPOINTMENT,
    REQUEST_START_STEP,
    REQUEST_FINISH_STEP,
    REQUEST_SUCCESS,
    REQUEST_FAILED
}
